### ISSUE TITLE
FreeSWITCH cannot see libks installed

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [signalwire/libks#116]
Hi,
I just compile and  installed on Fedora 34 64bits libks in default folder /usr/lib
but freeswitch compilation still complains to not find it.
any idea?

**Comment by ROBERT-MCDOWELL** [comment]
ok I had to force to install it in /usr/local
cmake . -DCMAKE_INSTALL_PREFIX:PATH=/usr/local

**Comment by ROBERT-MCDOWELL** [comment]
..

**Comment by ROBERT-MCDOWELL** [comment]
...

**Comment by andywolk** [comment]
We do not support Fedora. But patches are welcome!

**Comment by ROBERT-MCDOWELL** [comment]
@andywolk
dunno GO but will check the condition if I can do it.

**Comment by ROBERT-MCDOWELL** [comment]
ok the trick is to replace Debian in CMakeCache.txt by Centos as Centos has the same structure than Fedora since it's based on RedHat
