### ISSUE TITLE
How to install it with apt-get?

### ISSUE THREAD

**Issue by evandrocoan** [signalwire/libks#14]

**Comment by andywolk** [comment]
Do you have a Jira account?
http://jira.freeswitch.org

**Comment by evandrocoan** [comment]
I do not have. Do I need one?

**Comment by andywolk** [comment]
Configure freeswitch public apt repo following this article and then do `apt-get install libks`:
https://freeswitch.org/confluence/display/FREESWITCH/Debian+9+Stretch
