### ISSUE TITLE
You need to either install libks2 or libks or disable mod_verto in modules.conf

### ISSUE THREAD

**Issue by voztovoice** [signalwire/libks#178]
I can't compile FreeSWITCH after installing links from sources. Rocky Linux 9 My Steps:

**cd /usr/src
git clone https://github.com/signalwire/libks.git
cd libks/
cmake .
make
make install
cd /usr/src**

**git clone -b v1.10 https://github.com/signalwire/freeswitch.git
cd freeswitch
./bootstrap.sh
./configure -C --enable-portable-binary \
            --prefix=/usr --localstatedir=/var --sysconfdir=/etc \
            --with-gnu-ld --with-python=/usr/bin/python3 --with-openssl \
            --enable-core-odbc-support --enable-zrtp \
            --enable-core-pgsql-support \
            --enable-static-v8 --disable-parallel-build-v8**

_checking for libks2 >= 2.0.0... checking for libks >= 1.8.2... configure: error: You need to either install libks2 or libks or disable mod_verto in modules.conf_

Any hint?

Regards

**Comment by mjerris** [comment]
https://github.com/signalwire/libks
