### ISSUE TITLE
core dump in kws.c

### ISSUE THREAD

**Issue by guiyongdong** [signalwire/libks#62]
when use kws_connect_ex to connect ws server, than it crash。
but i can not find any nil。

libks version: v2.0 
commit: 0226f341fd951e22a978784f5e498fb6df2408aa

![image](https://user-images.githubusercontent.com/14196519/76220023-b95d6480-6251-11ea-8239-b4b0e8e3ff5d.png)

**Comment by mjerris** [comment]
v2.0 is not in public release yet.  current public use of the code should be off the master branch.  all public code that uses it is designed to use the master branch.

**Comment by guiyongdong** [comment]
Thank you
