### ISSUE TITLE
error: ‘CRYPTO_MEM_CHECK_ON’ undeclared 

### ISSUE THREAD

**Issue by spinlockirqsave** [signalwire/libks#79]
pi@raspberrypi:~/projects/libks $ make
Scanning dependencies of target ks
[  1%] Building C object CMakeFiles/ks.dir/src/ks.c.o
[  2%] Building C object CMakeFiles/ks.dir/src/ks_acl.c.o
[  3%] Building C object CMakeFiles/ks.dir/src/ks_base64.c.o
[  4%] Building C object CMakeFiles/ks.dir/src/ks_buffer.c.o
[  5%] Building C object CMakeFiles/ks.dir/src/ks_config.c.o
[  7%] Building C object CMakeFiles/ks.dir/src/ks_debug.c.o
[  8%] Building C object CMakeFiles/ks.dir/src/ks_dso.c.o
[  9%] Building C object CMakeFiles/ks.dir/src/ks_env.c.o
[ 10%] Building C object CMakeFiles/ks.dir/src/ks_handle.c.o
[ 11%] Building C object CMakeFiles/ks.dir/src/ks_hash.c.o
[ 13%] Building C object CMakeFiles/ks.dir/src/ks_json.c.o
[ 14%] Building C object CMakeFiles/ks.dir/src/ks_json_check.c.o
[ 15%] Building C object CMakeFiles/ks.dir/src/ks_log.c.o
[ 16%] Building C object CMakeFiles/ks.dir/src/ks_metrics.c.o
[ 17%] Building C object CMakeFiles/ks.dir/src/ks_mutex.c.o
[ 19%] Building C object CMakeFiles/ks.dir/src/ks_pool.c.o
[ 20%] Building C object CMakeFiles/ks.dir/src/ks_printf.c.o
[ 21%] Building C object CMakeFiles/ks.dir/src/ks_q.c.o
[ 22%] Building C object CMakeFiles/ks.dir/src/ks_sb.c.o
[ 23%] Building C object CMakeFiles/ks.dir/src/ks_socket.c.o
[ 25%] Building C object CMakeFiles/ks.dir/src/ks_ssl.c.o
/home/pi/projects/libks/src/ks_ssl.c: In function ‘ks_gen_cert’:
/home/pi/projects/libks/src/ks_ssl.c:134:2: warning: implicit declaration of function ‘CRYPTO_mem_ctrl’ [-Wimplicit-function-declaration]
  CRYPTO_mem_ctrl(CRYPTO_MEM_CHECK_ON);
  ^~~~~~~~~~~~~~~
/home/pi/projects/libks/src/ks_ssl.c:134:18: error: ‘CRYPTO_MEM_CHECK_ON’ undeclared (first use in this function)
  CRYPTO_mem_ctrl(CRYPTO_MEM_CHECK_ON);
                  ^~~~~~~~~~~~~~~~~~~
/home/pi/projects/libks/src/ks_ssl.c:134:18: note: each undeclared identifier is reported only once for each function it appears in
/home/pi/projects/libks/src/ks_ssl.c: In function ‘mkcert’:
/home/pi/projects/libks/src/ks_ssl.c:218:9: warning: ‘RSA_generate_key_ex’ is deprecated [-Wdeprecated-declarations]
         RSA_generate_key_ex(rsa, bits, BN_value_RSA_F4, NULL);
         ^~~~~~~~~~~~~~~~~~~
In file included from /usr/local/include/openssl/opensslv.h:109:0,
                 from /usr/local/include/openssl/macros.h:11,
                 from /usr/local/include/openssl/opensslconf.h:14,
                 from /usr/local/include/openssl/macros.h:10,
                 from /usr/local/include/openssl/ssl.h:16,
                 from /home/pi/projects/libks/src/include/libks/ks_ssl.h:25,
                 from /home/pi/projects/libks/src/include/libks/ks.h:73,
                 from /home/pi/projects/libks/src/ks_ssl.c:23:
/usr/local/include/openssl/rsa.h:249:1: note: declared here
 DEPRECATEDIN_3_0(int RSA_generate_key_ex(RSA *rsa, int bits, BIGNUM *e,
 ^
CMakeFiles/ks.dir/build.make:590: recipe for target 'CMakeFiles/ks.dir/src/ks_ssl.c.o' failed
make[2]: *** [CMakeFiles/ks.dir/src/ks_ssl.c.o] Error 1
CMakeFiles/Makefile2:99: recipe for target 'CMakeFiles/ks.dir/all' failed
make[1]: *** [CMakeFiles/ks.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by mjerris** [comment]
what operating system and version of openssl?
