### ISSUE TITLE
cmake. error

### ISSUE THREAD

**Issue by PrateekGoyal18** [signalwire/libks#91]
Trying to build the src files and getting this error

Checking for module 'uuid'
No package 'uuid' found
CMake Error at /usr/share/cmake-3.16/Modules/FindPkgConfig.cmake:463 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPkgConfig.cmake:643 (_pkg_check_modules_internal)
  cmake/FindUUID.cmake:15 (pkg_check_modules)
  CMakeLists.txt:411 (include)

Configuring incomplete, errors occurred!
See also "/usr/src/libks/CMakeFiles/CMakeOutput.log".
executor failed running [/bin/sh -c cmake .]: exit code: 1

**Comment by PrateekGoyal18** [comment]
There was a dependency error.

**Comment by n8twj** [comment]
what was the missing dependency?

**Comment by Changcumt** [comment]
System: centos 7
run it:
`yum install -y libuuid-devel`
